version: '3'

services:
  db:
    hostname: db
    user: $UID
    image: mongo
    ports:
    - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: web
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
    volumes:
    - ./docker/data:/data/db
    - ./initmongo.sh:/docker-entrypoint-initdb.d/initmongo.sh
  mqtt:
    hostname: mqtt
    image: eclipse-mosquitto
    ports:
    - '1883:1883'
    - '9001:9001'
    volumes:
    - ./docker/mqtt/config:/mosquitto/config/
    - ./docker/mqtt/data:/mosquitto/data/
  web:
    hostname: web
    image: web_app
    ports:
    - 80:8080
    volumes:
    - ./application:/app
